#!/bin/bash

# Check and update latest stable ktlint version
check_ktlint_version() {
    LATEST_VERSION=$(brew info --json=v1 ktlint | jq -r '.[0].versions.stable')

    if ! command -v ktlint &> /dev/null; then
        echo "Installing ktlint..."
        HOMEBREW_NO_AUTO_UPDATE=1 brew install ktlint
    else
        KT_VERSION=$(ktlint -v | awk '{print $3}')

        if [[ "$KT_VERSION" != "$LATEST_VERSION" ]]; then
            echo "Upgrading ktlint from version $KT_VERSION to $LATEST_VERSION..."
            brew upgrade ktlint
            KT_VERSION=$LATEST_VERSION
        else
            echo "ktlint is up-to-date with the latest version: $KT_VERSION"
        fi
    fi
}

# Run ktlint and automatically stage formatted files
run_ktlint() {
    echo -e "\nRunning ktlint to format code...\n"
    ktlint -F "*/src/**/*.kt"

    formatted_files=$(git status --porcelain '*/src/**/*.kt' | wc -l)
    if [ "$formatted_files" -eq 0 ]; then
        echo "No changes detected after formatting."
    else
        echo "Changes detected after formatting:"
        git status --porcelain '*/src/**/*.kt' | awk '{print $2}' | xargs git add
        echo "Staged changes for commit."
    fi

    echo -e "\nCode formatted successfully.\n"
}

# Main
check_ktlint_version
run_ktlint
