#!/bin/bash

MINIMAL_VERSION="1.3.0"

# Check ktlint version
KT_VERSION=$(ktlint -v | awk '{print $3}')

# Compare versions
if [[ "$(printf '%s\n' "$MINIMAL_VERSION" "$KT_VERSION" | sort -V | head -n1)" != "$MINIMAL_VERSION" ]]; then
    echo "Warning: Your ktlint version ($KT_VERSION) is lower than the minimal required version ($MINIMAL_VERSION). Upgrading..."
    brew upgrade ktlint
elif [[ "$KT_VERSION" > "$MINIMAL_VERSION" ]]; then
    echo -e "\e[33mWarning: Your ktlint version ($KT_VERSION) is higher than the minimal required version ($MINIMAL_VERSION)."
    echo "This could result in different behavior. Consider upgrading the minimal version."
fi

echo "ktlint version: $KT_VERSION"

echo "Pre commit: Formats the code with ktlint (install with brew install ktlint) ..."
echo ""
ktlint -F "*/src/**/*.kt"

KT_EXIT_CODE=$?

if [ $KT_EXIT_CODE -ne 0 ]; then
    echo "Error: 'ktlint -F \"*/src/**/*.kt\"' failed. Please fix the issues before committing."
    exit 1
fi
