#!/bin/bash

# Get the latest stable version of ktlint
LATEST_VERSION=$(brew info --json=v1 ktlint | jq -r '.[0].versions.stable')

check_ktlint_version() {
    if ! command -v ktlint &> /dev/null; then
        echo "Installing ktlint..."
        brew install ktlint
    else
        KT_VERSION=$(ktlint -v | awk '{print $3}')

        if [[ "$KT_VERSION" != "$LATEST_VERSION" ]]; then
            echo "Upgrading ktlint from version $KT_VERSION to $LATEST_VERSION..."
            brew upgrade ktlint
            KT_VERSION=$LATEST_VERSION
        else
            echo "ktlint is already the latest version: $KT_VERSION"
            echo
        fi
    fi
}

run_ktlint() {
    local ktlint_command="ktlint -F '*/src/**/*.kt'"
    echo "Running ktlint to check code formatting..."
    echo
    ktlint_output=$($ktlint_command 2>&1)
    KT_EXIT_CODE=$?

    if [ $KT_EXIT_CODE -ne 0 ]; then
        echo "Warning: 'ktlint -F \"*/src/**/*.kt\"' found formatting issues."
        echo "$ktlint_output"
    else
        echo "No formatting issues found."
    fi
}

check_ktlint_version
run_ktlint
